import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
// Pure local mode - no Google Auth or cookies required
import fs from "fs";
import * as dotenv from "dotenv";

// Explicitly load the root .env where the GEMINI_API_KEY lives
dotenv.config({ path: "/Users/ryanthomson/Github/LTX-Local-Studio-Manager/.env" });

import { startDaemon, stopDaemon, getDaemonStatus } from "./daemon_manager.ts";
import { runAutonomousScrape } from "./scraper_service.ts";

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '50mb' }));
  // Local studio mode - no OAuth required

  // API routes
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // Daemon Management
  app.post("/api/daemon/start", (req, res) => {
    const result = startDaemon();
    res.json(result);
  });

  app.post("/api/daemon/stop", (req, res) => {
    const result = stopDaemon();
    res.json(result);
  });

  app.get("/api/daemon/status", (req, res) => {
    res.json(getDaemonStatus());
  });

  // Autonomous Scraping
  app.post("/api/curate/autonomous", async (req, res) => {
    const { queries } = req.body;
    if (!queries || !Array.isArray(queries)) {
      return res.status(400).json({ error: "Queries must be an array" });
    }

    console.log(`\n[STUDIO MANAGER 📡] Received Autonomous Scrape request from the 5090 Engine.`);
    console.log(`[STUDIO MANAGER 📡] Target Queries: ${queries.join(", ")}`);
    console.log(`[STUDIO MANAGER 🚀] Dispatching to Gemini 3.1 Flash-Lite Engine in background...`);
    
    // Run in background to avoid timeout
    queries.forEach(async (query) => {
        await runAutonomousScrape(query);
    });

    res.json({ success: true, message: "Autonomous scraping started in background." });
  });

  // --- Local Dataset Management ---
  const workspaceRoot = "/Users/ryanthomson/Github/LTX-Local-Studio-Manager";
  const dataDir = path.join(workspaceRoot, "services/Training Data");

  app.post("/api/dataset/save", async (req, res) => {
    const { dataset } = req.body;
    if (!Array.isArray(dataset)) {
      return res.status(400).json({ error: "Dataset must be an array" });
    }
    try {
      if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
      }
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `extraction_${timestamp}.json`;
      const filePath = path.join(dataDir, filename);
      
      fs.writeFileSync(filePath, JSON.stringify(dataset, null, 2), 'utf8');
      console.log(`[LOCAL STUDIO] Saved dataset with ${dataset.length} entries to ${filePath}`);
      res.json({ success: true, local_path: filePath });
    } catch (error) {
      console.error("Local save error", error);
      res.status(500).json({ error: "Failed to save to local disk" });
    }
  });

  app.get("/api/dataset/load", async (req, res) => {
    try {
      if (!fs.existsSync(dataDir)) {
        return res.json({ dataset: [] });
      }
      
      // Look for the clean_training_set.jsonl generated by the Python Max-Audit script
      const cleanPath = path.join(dataDir, "clean_training_set.jsonl");
      if (fs.existsSync(cleanPath)) {
        const content = fs.readFileSync(cleanPath, 'utf8');
        const dataset = content.split('\\n').filter(line => line.trim()).map(line => JSON.parse(line));
        console.log(`[LOCAL STUDIO] Loaded ${dataset.length} entries from clean_training_set.jsonl`);
        return res.json({ dataset });
      }
      
      // Fallback: Read all extraction_*.json files
      const files = fs.readdirSync(dataDir).filter(f => f.startsWith('extraction_') && f.endsWith('.json'));
      let combinedDataset: any[] = [];
      for (const file of files) {
         const content = JSON.parse(fs.readFileSync(path.join(dataDir, file), 'utf8'));
         if (Array.isArray(content)) combinedDataset.push(...content);
      }
      console.log(`[LOCAL STUDIO] Loaded ${combinedDataset.length} entries from raw extraction files`);
      res.json({ dataset: combinedDataset });

    } catch (error) {
      console.error("Local load error", error);
      res.status(500).json({ error: "Failed to load local dataset" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true, host: '0.0.0.0' },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[STUDIO MANAGER] Server running on all interfaces (including Tailscale) at port ${PORT}`);
  });
}

startServer();
